// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
#pragma warning disable 1591, 3008, 3009, 0108
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ShareTube.Controllers
{
    public partial class ShareTubeController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ShareTubeController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WatchLoginCallback()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WatchLoginCallback);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Watch()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Watch);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult WatchYT()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WatchYT);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PlaylistEntry()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PlaylistEntry);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SearchResults()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchResults);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ShareTubeController Actions { get { return MVC.ShareTube; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ShareTube";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ShareTube";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string NewRoom = "NewRoom";
            public readonly string WatchLoginCallback = "WatchLoginCallback";
            public readonly string Watch = "Watch";
            public readonly string WatchYT = "WatchYT";
            public readonly string RoomList = "RoomList";
            public readonly string RoomListAjax = "RoomListAjax";
            public readonly string PlaylistEntry = "PlaylistEntry";
            public readonly string SearchResults = "SearchResults";
            public readonly string ClearEmptyRooms = "ClearEmptyRooms";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string NewRoom = "NewRoom";
            public const string WatchLoginCallback = "WatchLoginCallback";
            public const string Watch = "Watch";
            public const string WatchYT = "WatchYT";
            public const string RoomList = "RoomList";
            public const string RoomListAjax = "RoomListAjax";
            public const string PlaylistEntry = "PlaylistEntry";
            public const string SearchResults = "SearchResults";
            public const string ClearEmptyRooms = "ClearEmptyRooms";
        }


        static readonly ActionParamsClass_NewRoom s_params_NewRoom = new ActionParamsClass_NewRoom();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NewRoom NewRoomParams { get { return s_params_NewRoom; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NewRoom
        {
            public readonly string room = "room";
        }
        static readonly ActionParamsClass_WatchLoginCallback s_params_WatchLoginCallback = new ActionParamsClass_WatchLoginCallback();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WatchLoginCallback WatchLoginCallbackParams { get { return s_params_WatchLoginCallback; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WatchLoginCallback
        {
            public readonly string id = "id";
            public readonly string loginFromConnectionID = "loginFromConnectionID";
        }
        static readonly ActionParamsClass_Watch s_params_Watch = new ActionParamsClass_Watch();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Watch WatchParams { get { return s_params_Watch; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Watch
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_WatchYT s_params_WatchYT = new ActionParamsClass_WatchYT();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WatchYT WatchYTParams { get { return s_params_WatchYT; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WatchYT
        {
            public readonly string v = "v";
        }
        static readonly ActionParamsClass_PlaylistEntry s_params_PlaylistEntry = new ActionParamsClass_PlaylistEntry();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PlaylistEntry PlaylistEntryParams { get { return s_params_PlaylistEntry; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PlaylistEntry
        {
            public readonly string vm = "vm";
        }
        static readonly ActionParamsClass_SearchResults s_params_SearchResults = new ActionParamsClass_SearchResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SearchResults SearchResultsParams { get { return s_params_SearchResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SearchResults
        {
            public readonly string vms = "vms";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string NewRoom = "NewRoom";
                public readonly string PlaylistEntry = "PlaylistEntry";
                public readonly string RoomList = "RoomList";
                public readonly string Watch = "Watch";
            }
            public readonly string Index = "~/Views/ShareTube/Index.cshtml";
            public readonly string NewRoom = "~/Views/ShareTube/NewRoom.cshtml";
            public readonly string PlaylistEntry = "~/Views/ShareTube/PlaylistEntry.cshtml";
            public readonly string RoomList = "~/Views/ShareTube/RoomList.cshtml";
            public readonly string Watch = "~/Views/ShareTube/Watch.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ShareTubeController : ShareTube.Controllers.ShareTubeController
    {
        public T4MVC_ShareTubeController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewRoomOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult NewRoom()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewRoom);
            NewRoomOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void NewRoomOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ShareTube.Data.Room room);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> NewRoom(ShareTube.Data.Room room)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewRoom);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "room", room);
            NewRoomOverride(callInfo, room);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void WatchLoginCallbackOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id, string loginFromConnectionID);

        [NonAction]
        public override System.Web.Mvc.ActionResult WatchLoginCallback(string id, string loginFromConnectionID)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WatchLoginCallback);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "loginFromConnectionID", loginFromConnectionID);
            WatchLoginCallbackOverride(callInfo, id, loginFromConnectionID);
            return callInfo;
        }

        [NonAction]
        partial void WatchOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string id);

        [NonAction]
        public override System.Threading.Tasks.Task<System.Web.Mvc.ActionResult> Watch(string id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Watch);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            WatchOverride(callInfo, id);
            return System.Threading.Tasks.Task.FromResult(callInfo as ActionResult);
        }

        [NonAction]
        partial void WatchYTOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string v);

        [NonAction]
        public override System.Web.Mvc.ActionResult WatchYT(string v)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WatchYT);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "v", v);
            WatchYTOverride(callInfo, v);
            return callInfo;
        }

        [NonAction]
        partial void RoomListOverride(T4MVC_System_Web_Mvc_PartialViewResult callInfo);

        [NonAction]
        public override System.Web.Mvc.PartialViewResult RoomList()
        {
            var callInfo = new T4MVC_System_Web_Mvc_PartialViewResult(Area, Name, ActionNames.RoomList);
            RoomListOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void RoomListAjaxOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult RoomListAjax()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RoomListAjax);
            RoomListAjaxOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void PlaylistEntryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ShareTube.Data.Video vm);

        [NonAction]
        public override System.Web.Mvc.ActionResult PlaylistEntry(ShareTube.Data.Video vm)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PlaylistEntry);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vm", vm);
            PlaylistEntryOverride(callInfo, vm);
            return callInfo;
        }

        [NonAction]
        partial void SearchResultsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<ShareTube.Data.Video> vms);

        [NonAction]
        public override System.Web.Mvc.ActionResult SearchResults(System.Collections.Generic.List<ShareTube.Data.Video> vms)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SearchResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "vms", vms);
            SearchResultsOverride(callInfo, vms);
            return callInfo;
        }

        [NonAction]
        partial void ClearEmptyRoomsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ClearEmptyRooms()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ClearEmptyRooms);
            ClearEmptyRoomsOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108
